host: 192.168.56.101
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    url: jdbc:mariadb://${host}/vhr
  data:
    redis:
      host: ${host}
server:
  servlet:
    context-path: /api
jimmer:
  language: kotlin
  show-sql: true
sa-token:
  token-name: token